version: "3.8"

services:
  db:
    image: postgres:16
    container_name: usedcars-db
    restart: always
    environment:
      POSTGRES_DB: usedcars
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5439:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
